### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'withFileTypes') when starting

### ISSUE THREAD

**Issue by jdeepee** [juntofoundation/flux#164]
Found from debug.log: 

```
(node:5249) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `flux --trace-warnings ...` to show where the warning was created)
[1m
UserData path
/home/user/.config/flux

AppData path
/home/user/.config

Log path
/home/user/.config/flux/logs

Using Resource path
/tmp/.mount_Flux-0Z08eP3/resources/packaged-resources/bin

built in language path

/tmp/.mount_Flux-0Z08eP3/resources/packaged-resources/languages
[36m%s[0m
Init AD4M...

[2m
Starting ad4m core with path:
/home/user/.config/flux


AD4M Bootstrap Languages:
{
  agents: 'agent-expression-store',
  languages: 'languages',
  neighbourhoods: 'neighbourhood-store'
}


AD4M Bootstrap Fixtures:
{ languages: [], neighbourhoods: [] }


Built-in languages path:
/tmp/.mount_Flux-0Z08eP3/resources/packaged-resources/languages


Built-In languages:
[]


=> All auto-loaded languages:
[ 'agent-expression-store', 'languages', 'neighbourhood-store' ]


Language aliases:
{
  did: 'agent-expression-store',
  lang: 'languages',
  neighbourhood: 'neighbourhood-store'
}


Resource path:
/tmp/.mount_Flux-0Z08eP3/resources/packaged-resources/bin


[0m
[34m
Init services...
[0m
Init HolochainService with data path: 
/home/user/.config/flux/ad4m/h/d
. Conductor path: 
/home/user/.config/flux/ad4m/h/c
. Resource path: 
/tmp/.mount_Flux-0Z08eP3/resources/packaged-resources/bin
Holochain ports: admin=2000 app=1337
HolochainService: Creating low-db instance for holochain-serivce
HolochainService: Writing fresh conductor file...
generating %s-bit (rsa only) %s keypair...
2048
RSA
#lair-keystore-dir:"/home/user/.config/flux/ad4m/h/c/keystore"#
#lair-keystore-ready#
#lair-keystore-version:0.0.7#

[2mOct 23 04:08:08.268[0m [32m INFO[0m holochain::conductor::conductor::builder: self.config=ConductorConfig { environment_path: EnvironmentRootPath("/home/user/.config/flux/ad4m/h/c"), use_dangerous_test_keystore: false, dpki: None, keystore_path: Some("/home/user/.config/flux/ad4m/h/c/keystore"), passphrase_service: DangerInsecureFromConfig { passphrase: "foobar" }, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 2000 } }]), network: Some(KitsuneP2pConfig { transport_pool: [Proxy { sub_transport: Quic { bind_to: None, override_host: None, override_port: None }, proxy_config: RemoteProxyClient { proxy_url: Url2 { url: "kitsune-proxy://SYVd4CF3BdJ4DS7KwLLgeU3_DbHoZ34Y-qroZ79DOs8/kitsune-quic/h/165.22.32.11/p/5779/--" } } }], bootstrap_service: Some(Url2 { url: "https://bootstrap-staging.holo.host/" }), tuning_params: KitsuneP2pTuningParams { gossip_strategy: "sharded-gossip", gossip_loop_iteration_delay_ms: 1000, gossip_outbound_target_mbps: 0.5, gossip_inbound_target_mbps: 0.5, gossip_historic_outbound_target_mbps: 0.1, gossip_historic_inbound_target_mbps: 0.1, gossip_peer_on_success_next_gossip_delay_ms: 60000, gossip_peer_on_error_next_gossip_delay_ms: 300000, gossip_local_sync_delay_ms: 60000, gossip_dynamic_arcs: false, gossip_single_storage_arc_per_space: false, default_rpc_single_timeout_ms: 30000, default_rpc_multi_remote_agent_count: 3, default_rpc_multi_remote_request_grace_ms: 3000, agent_info_expires_after_ms: 1200000, tls_in_mem_session_storage: 512, proxy_keepalive_ms: 120000, proxy_to_expire_ms: 300000, concurrent_limit_per_thread: 4096, tx2_quic_max_idle_timeout_ms: 30000, tx2_pool_max_connection_count: 4096, tx2_channel_count_per_connection: 16, tx2_implicit_timeout_ms: 30000, tx2_initial_connect_retry_delay_ms: 200 }, network_type: QuicBootstrap }), db_sync_level: Normal }
[2mOct 23 04:08:08.275[0m [33m WARN[0m holochain::conductor::conductor::builder: USING INSECURE PASSPHRASE FROM CONFIG--This defeats the whole purpose of having a passphrase. (unfortunately, there isn't another option at the moment).

[2mOct 23 04:08:08.931[0m [32m INFO[0m holochain_sqlite::schema: database initialized: Conductor

[2mOct 23 04:08:08.956[0m [32m INFO[0m holochain_sqlite::schema: database initialized: Wasm

[2mOct 23 04:08:09.062[0m [32m INFO[0m kitsune_p2p_transport_quic::tx2: bound local endpoint (quic) local_cert=Cert(xD493R..M3sgSY) url=kitsune-quic://192.168.1.4:59046

[2mOct 23 04:08:09.062[0m [32m INFO[0m kitsune_p2p::spawn::actor: this_addr: kitsune-proxy://xD493RbysjrMxmY5mCmnCyD6zRgsEFOAROo4LM3sgSY/kitsune-quic/h/165.22.32.11/p/5779/--


###HOLOCHAIN_SETUP###
###ADMIN_PORT:2000###
###HOLOCHAIN_SETUP_END###

[2mOct 23 04:08:09.107[0m [32m INFO[0m holochain: Conductor successfully initialized.

Conductor ready.

HolochainService: Holochain running... Attempting connection



HolochainService: Holochain admin interface connected on port
2000
HolochainService: Holochain app interface connected on port
1337
[2mOct 23 04:08:09.288[0m [32m INFO[0m kitsune_p2p_transport_quic::tx2: established outgoing connection (quic) local_cert=Cert(xD493R..M3sgSY) peer_cert=Cert(SYVd4C..79DOs8) url=kitsune-quic://165.22.32.11:5779
[2mOct 23 04:08:09.288[0m [32m INFO[0m kitsune_p2p_types::tx2::tx2_pool_promote: establish outgoing connection (pool) elapsed_s=0.225579069 local_cert=Cert(xD493R..M3sgSY) peer_cert=Cert(SYVd4C..79DOs8) url=kitsune-quic://165.22.32.11:5779

Ad4m init error:
TypeError: Cannot read properties of null (reading 'withFileTypes')
    at e.readdir (node:electron/js2c/asar_bundle:5:10202)
    at go$readdir (/tmp/.mount_Flux-0Z08eP3/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:201:14)
    at Object.readdir (/tmp/.mount_Flux-0Z08eP3/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:198:12)
    at /tmp/.mount_Flux-0Z08eP3/resources/app.asar/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.readdir (/tmp/.mount_Flux-0Z08eP3/resources/app.asar/node_modules/universalify/index.js:7:14)
    at _glob (/tmp/.mount_Flux-0Z08eP3/resources/app.asar/node_modules/it-glob/index.js:54:38)
    at _glob.next (<anonymous>)
    at glob (/tmp/.mount_Flux-0Z08eP3/resources/app.asar/node_modules/it-glob/index.js:34:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2mOct 23 04:08:22.287[0m [32m INFO[0m kitsune_p2p_types::metrics: sys_info=MetricSysInfo { used_mem_kb: 24012, proc_cpu_usage_pct_1000: 0, tx_bytes_per_sec: 266, rx_bytes_per_sec: 172, sends_per_sec: 0, recvs_per_sec: 0, tokio_task_count: 2, avg_pool_buf_release_size: 0, avg_api_req_res_elapsed_ms: 0 }


```

**Comment by kaichaosun** [comment]
Fedora is fixed with 0.2.10,
helpful commands,
```shell
chmod a+x Flux-0.2.10.AppImage
./Flux-0.2.10.AppImage
```
